### ISSUE TITLE
[EPIC] Further protocol development roadmap

### ISSUE THREAD

**Issue by dr-orlovsky** [pandoracore/prometheus-spec#9]
- [ ] Use channel factories so the whole set of transactions can move into a network under single large multiparty channel (with all workers, validators and prospective clients participating it). Additionally channel splits may allow simplification of how new parties join this network. This solves scalability problem.
- [ ] Use RGB with public state to build off-chain information exchange between parties performing computational contract and link it to a transaction graph from a computation channel created by the channel factory. This will simplify interaction & data exchange protocol and will help to build reputational system for the next steps operating over ephemeral LN state (basically reputation is created by the signatures of contract participants with a copy payment transactions attached)
- [ ] Use specially-designed blockchain (with aggregatable history) for consensus on list of availiable validators. It must be PoW, either with a new algo, or with merged mining to bitcoin. This will allow more stable arbitration system utilizing reputation and random selection of participants
